# Sample .travis.yml for R projects

language: r
cache: packages
warnings_are_errors: false
sudo: required
dist: trusty

env:
   global:
     - _R_CHECK_FORCE_SUGGESTS_=FALSE

notifications:
  email:
    on_success: change
    on_failure: change

apt_packages:
  - libgsl0-dev
os:
  - linux

# Binary versions of packages to reduce build time.
r_binary_packages:
  - data.table
  - dplyr
  - markdown
  - readr
  - rlang
  - rmarkdown
  - stringi
  - tidyr
  - tibble
  - ggplot2
  - pbmcapply
  - adespatial
  - missRanger
  - ape
  - adespatial,
  - cowplot,
  - ggpubr,
  - vegan
  - xgboost
  - randomForestSRC
