# Sample .travis.yml for R projects

language: r
cache: packages
warnings_are_errors: false
sudo: required
dist: trusty

env:
   global:
     - _R_CHECK_FORCE_SUGGESTS_=FALSE



notifications:
  email:
    on_success: change
    on_failure: change

apt_packages:
  - libgsl0-dev
os:
  - linux
  - osx
