---
  title: "Installation problems"
  author: "Thierry Gosselin"
  date: "`r Sys.Date()`"
  output: rmarkdown::html_vignette
# output: 
# pdf_document:
  vignette: >
    %\VignetteIndexEntry{"Installation problems"}
    %\VignetteEngine{knitr::rmarkdown}
    \usepackage[utf8]{inputenc}
---

1. Sometimes you'll get warnings while installing dependencies required for **grur** or other R packages.
```r
Warning: cannot remove prior installation of package ‘stringi’
```
To solve this problem, delete manually the problematic package in the installation folder (on mac: `/Library/Frameworks/R.framework/Resources/library`) or in the `Terminal`:
```r
sudo rm -R /Library/Frameworks/R.framework/Resources/library/package_name
# Changing 'package_name' to the problematic package.
# Reinstall the package.
```

2. Using the latest version of R, RStudio and packages is recommended.

3. Look at the output in R console when you get an error message. If it's related to
one's of `grur` numerous dependencies, try installing it separately before attempting
to reinstall `grur`.

4. Linux related problem

    If you have an install problem, and that `grur` build badges on the main 
    `grur` github page are green, the problem is with some dependencies and
    are very computer-specific.
    
    e.g. if the problem is related to `strataG`, `copula` and/or `gsl`, try
installing `libgsl0-dev` in the **Terminal** (very easy now with the latest RStudio release!):
```
 sudo apt-get install libgsl0-dev
```
